# Generated by Django 4.1 on 2022-08-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_bx', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='ID задачи в BX24')),
                ('status', models.CharField(max_length=50, verbose_name='Название направления')),
            ],
            options={
                'verbose_name': 'Последний статус задачи',
                'verbose_name_plural': 'Последние статусы задач',
            },
        ),
    ]
